# Generated by Django 4.1.7 on 2023-03-18 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('box_number', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=20)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_date', models.DateField()),
                ('rental_duration', models.IntegerField()),
                ('billing_amount', models.FloatField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boxes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employees')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employees'),
        ),
    ]
