# Generated by Django 4.1.7 on 2023-03-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='emp',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='employee',
        ),
    ]
