# Generated by Django 4.1.7 on 2023-03-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_boxes_box_rename_clients_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='islast',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
