# Generated by Django 4.1.7 on 2023-03-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_transaction_islast'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=1002, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=101, max_length=255),
            preserve_default=False,
        ),
    ]
