# Generated by Django 4.1.7 on 2023-03-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_client_eye_color_alter_client_hair_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
