# Generated by Django 4.1.7 on 2023-03-24 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_first_name_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='employee',
        ),
        migrations.CreateModel(
            name='Visitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_time', models.TimeField()),
                ('visit_date', models.DateField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.box')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
