# Generated by Django 4.1.7 on 2023-03-24 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_client_employee_visitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitation',
            old_name='visit_time',
            new_name='check_in',
        ),
        migrations.AddField(
            model_name='visitation',
            name='check_out',
            field=models.TimeField(default=datetime.datetime(2023, 3, 24, 10, 19, 50, 678138, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
