# Generated by Django 4.1.7 on 2023-03-25 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_visit_time_visitation_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 19, 21, 49, 67372, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='firm_location',
            field=models.CharField(default='firm', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='firm_name',
            field=models.CharField(default='firm', max_length=255),
            preserve_default=False,
        ),
    ]
