# Generated by Django 4.1.7 on 2023-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_client_birthdate_client_firm_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pic_url',
            field=models.TextField(default='url'),
            preserve_default=False,
        ),
    ]
